# Generated by Django 5.0.6 on 2024-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('month', models.CharField(choices=[('January', 'Jan'), ('February', 'Fab'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='December', max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product/recent_blog/')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='chairs',
            name='image',
            field=models.ImageField(default=1, upload_to='product/chairs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chairs',
            name='price',
            field=models.CharField(choices=[('UZD', 'Sum'), ('USD', '$')], default='UZD', max_length=10),
        ),
        migrations.CreateModel(
            name='Testominal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('full_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='product/testominal/')),
                ('speciality', models.ManyToManyField(to='product.speciality')),
            ],
        ),
    ]
