# Generated by Django 5.0.6 on 2024-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rcentblog_speciality_chairs_image_chairs_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairs',
            name='prices',
            field=models.FloatField(default=30),
        ),
    ]
