# Generated by Django 5.0.6 on 2024-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_chairs_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairs',
            name='definition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
