# Generated by Django 5.0.6 on 2024-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_rcentblog_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcentblog',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
