# Generated by Django 5.0.6 on 2024-06-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_rcentblog_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcentblog',
            name='month',
        ),
    ]
