# Generated by Django 5.0.6 on 2024-06-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RcentBlog',
        ),
    ]
