# Generated by Django 5.0.6 on 2024-06-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairs',
            name='price',
            field=models.CharField(choices=[('UZD', 'Sum'), ('USD', '$')], default='UZD', max_length=50),
        ),
    ]
