# Generated by Django 5.0.6 on 2024-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_chairs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairs',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
