# Generated by Django 5.0.6 on 2024-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcentblog',
            name='image',
            field=models.ImageField(upload_to='blog/recent_blog/'),
        ),
    ]
